[project]
name = "paper-research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CuitSuanNaiGaiGai", email = "a1094819060s@qq.com" }
]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "httpx>=0.28.1",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.0",
    "playwright>=1.62.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
paper-research-agent = "paper_research_agent:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
